import type {
  Layout,
  Material,
  MaterialStream,
  Pattern,
  Producer,
  Product,
  Technique,
} from "./types";

export const PRODUCTS: readonly Product[] = [
  {
    slug: "tablecloth",
    name: "Tablecloth",
    category: "home-textiles",
    defaultWidthCm: 150,
    defaultHeightCm: 220,
    fabricUse: "38m of 42m",
    costPerUnitGbp: 16,
    previewMode: "flat",
    fixedSize: false,
    order: 1,
  },
  {
    slug: "cushion-cover",
    name: "Cushion cover",
    category: "home-textiles",
    defaultWidthCm: 45,
    defaultHeightCm: 45,
    fabricUse: "0.6m/cover",
    costPerUnitGbp: 9,
    previewMode: "flat",
    fixedSize: false,
    order: 2,
  },
  {
    slug: "curtain",
    name: "Curtain",
    category: "home-textiles",
    defaultWidthCm: 140,
    defaultHeightCm: 240,
    fabricUse: "3.5m/panel",
    costPerUnitGbp: 14,
    previewMode: "flat",
    fixedSize: false,
    order: 3,
  },
  {
    slug: "apron",
    name: "Apron",
    category: "home-textiles",
    defaultWidthCm: 70,
    defaultHeightCm: 90,
    fabricUse: "1.2m/apron",
    costPerUnitGbp: 10,
    previewMode: "flat",
    fixedSize: false,
    order: 4,
  },
  {
    slug: "tote-bag",
    name: "Tote bag",
    category: "garments-accessories",
    defaultWidthCm: 38,
    defaultHeightCm: 42,
    fabricUse: "4 panels/bag",
    costPerUnitGbp: 12,
    previewMode: "tote",
    fixedSize: true,
    order: 5,
  },
  {
    slug: "scarf",
    name: "Scarf",
    category: "garments-accessories",
    defaultWidthCm: 60,
    defaultHeightCm: 180,
    fabricUse: "1.2m/band",
    costPerUnitGbp: 8,
    previewMode: "scarf",
    fixedSize: true,
    order: 6,
  },
  {
    slug: "pouch",
    name: "Pouch",
    category: "garments-accessories",
    defaultWidthCm: 25,
    defaultHeightCm: 18,
    fabricUse: "0.3m/pouch",
    costPerUnitGbp: 6,
    previewMode: "scarf",
    fixedSize: true,
    order: 7,
  },
  {
    slug: "bandana",
    name: "Bandana",
    category: "garments-accessories",
    defaultWidthCm: 55,
    defaultHeightCm: 55,
    fabricUse: "0.4m/bandana",
    costPerUnitGbp: 5,
    previewMode: "scarf",
    fixedSize: true,
    order: 8,
  },
  {
    slug: "fabric-roll",
    name: "Fabric roll",
    category: "unfinished-material",
    defaultWidthCm: 150,
    defaultHeightCm: 42,
    fabricUse: "42m roll",
    costPerUnitGbp: 4,
    previewMode: "flat",
    fixedSize: true,
    order: 9,
  },
  {
    slug: "panel-lot",
    name: "Panel lot",
    category: "unfinished-material",
    defaultWidthCm: 45,
    defaultHeightCm: 60,
    fabricUse: "120 panels",
    costPerUnitGbp: 3,
    previewMode: "flat",
    fixedSize: true,
    order: 10,
  },
  {
    slug: "material-bundle",
    name: "Material bundle",
    category: "unfinished-material",
    defaultWidthCm: 100,
    defaultHeightCm: 100,
    fabricUse: "25kg bundle",
    costPerUnitGbp: 2,
    previewMode: "flat",
    fixedSize: true,
    order: 11,
  },
];

export const MATERIALS: readonly Material[] = [
  {
    slug: "linen",
    stream: "deadstock",
    sourceLabel: "New Deadstock · Pakistan",
    name: "Natural Linen Blend",
    available: "42m",
    width: "150cm",
    color: "Natural beige",
    bestFor: ["tablecloths", "napkins", "aprons", "cushion covers"],
    order: 1,
  },
  {
    slug: "twill",
    stream: "deadstock",
    sourceLabel: "New Deadstock · India",
    name: "Cotton Twill",
    available: "60m",
    width: "160cm",
    color: "Charcoal",
    bestFor: ["aprons", "totes", "workwear panels", "cushion covers"],
    order: 2,
  },
  {
    slug: "denim",
    stream: "reclaimed",
    sourceLabel: "Reclaimed · Fleek Pakistan",
    name: "Denim Panel Lot",
    available: "120 panels",
    width: "45×60cm",
    color: "Mixed indigo",
    bestFor: ["patchwork totes", "cushions", "jackets", "appliqué"],
    order: 3,
  },
  {
    slug: "shirt",
    stream: "reclaimed",
    sourceLabel: "Reclaimed · Fleek India",
    name: "Shirt Cotton Bundle",
    available: "80 panels",
    width: "40×55cm",
    color: "Blue stripe",
    bestFor: ["patchwork shirts", "linings", "scarves", "accessories"],
    order: 4,
  },
  {
    slug: "knit",
    stream: "reclaimed",
    sourceLabel: "Reclaimed · Fleek Pakistan",
    name: "Knit Bundle",
    available: "25kg",
    width: "Sorted knit",
    color: "Mixed neutral",
    bestFor: ["patchwork cushions", "soft accessories", "appliqué"],
    order: 5,
  },
  {
    slug: "hemp",
    stream: "deadstock",
    sourceLabel: "New Deadstock · Turkey",
    name: "Hemp Canvas Roll",
    available: "38m",
    width: "140cm",
    color: "Natural oat",
    bestFor: ["totes", "aprons", "upholstery panels", "heavy-duty accessories"],
    order: 6,
  },
  {
    slug: "poplin",
    stream: "deadstock",
    sourceLabel: "New Deadstock · Portugal",
    name: "Organic Cotton Poplin",
    available: "55m",
    width: "150cm",
    color: "Off-white",
    bestFor: ["shirts", "linings", "bandanas", "lightweight home textiles"],
    order: 7,
  },
  {
    slug: "chambray",
    stream: "deadstock",
    sourceLabel: "New Deadstock · Vietnam",
    name: "Chambray Shirting",
    available: "48m",
    width: "145cm",
    color: "Light indigo",
    bestFor: ["shirts", "scarves", "casual aprons", "relaxed home textiles"],
    order: 8,
  },
  {
    slug: "velvet",
    stream: "deadstock",
    sourceLabel: "New Deadstock · Italy",
    name: "Cotton Velvet Remnant",
    available: "22m",
    width: "135cm",
    color: "Deep burgundy",
    bestFor: ["cushion covers", "curtains", "pouches", "luxury accessories"],
    order: 9,
  },
  {
    slug: "canvas",
    stream: "deadstock",
    sourceLabel: "New Deadstock · UK",
    name: "Recycled Cotton Canvas",
    available: "70m",
    width: "155cm",
    color: "Unbleached natural",
    bestFor: ["tote bags", "workwear", "heavy aprons", "structured accessories"],
    order: 10,
  },
  {
    slug: "corduroy",
    stream: "reclaimed",
    sourceLabel: "Reclaimed · Fleek India",
    name: "Corduroy Panel Lot",
    available: "95 panels",
    width: "42×58cm",
    color: "Mixed earth",
    bestFor: ["patchwork jackets", "bags", "cushion panels", "warm accessories"],
    order: 11,
  },
  {
    slug: "fleece",
    stream: "reclaimed",
    sourceLabel: "Reclaimed · Fleek Pakistan",
    name: "Fleece Panel Lot",
    available: "60 panels",
    width: "38×50cm",
    color: "Mixed grey",
    bestFor: ["warm linings", "pouches", "soft accessories", "patchwork throws"],
    order: 12,
  },
  {
    slug: "wool",
    stream: "reclaimed",
    sourceLabel: "Reclaimed · Fleek UK",
    name: "Wool Flannel Bundle",
    available: "18kg",
    width: "Sorted flannel",
    color: "Mixed plaid",
    bestFor: ["scarves", "warm accessories", "patchwork throws", "lining panels"],
    order: 13,
  },
  {
    slug: "sari",
    stream: "reclaimed",
    sourceLabel: "Reclaimed · Fleek India",
    name: "Sari Silk Bundle",
    available: "40 panels",
    width: "90×120cm",
    color: "Mixed jewel",
    bestFor: [
      "scarves",
      "bandanas",
      "decorative cushions",
      "statement accessories",
    ],
    order: 14,
  },
  {
    slug: "terry",
    stream: "reclaimed",
    sourceLabel: "Reclaimed · Fleek UK",
    name: "Terry Cloth Bundle",
    available: "30kg",
    width: "Sorted terry",
    color: "Mixed pastel",
    bestFor: [
      "towels",
      "spa textiles",
      "bath accessories",
      "absorbent home goods",
    ],
    order: 15,
  },
];

export const MATERIAL_SLUGS = [
  "linen",
  "twill",
  "denim",
  "shirt",
  "knit",
  "hemp",
  "poplin",
  "chambray",
  "velvet",
  "canvas",
  "corduroy",
  "fleece",
  "wool",
  "sari",
  "terry",
] as const;

// The AI enum and this catalog must stay in lockstep; this assignment fails to
// type-check if either list gains or loses a slug.
const _materialSlugParity: readonly (typeof MATERIAL_SLUGS)[number][] =
  MATERIALS.map((material) => material.slug as (typeof MATERIAL_SLUGS)[number]);
void _materialSlugParity;

const TECHNIQUE_ROWS: readonly [
  string,
  string,
  Technique["kind"],
  MaterialStream[],
][] = [
  ["cut-sew", "Cut & sew", "construction", ["deadstock", "reclaimed"]],
  ["embroidery", "Embroidery", "surface", ["deadstock", "reclaimed"]],
  ["laser", "Laser etching", "surface", ["deadstock", "reclaimed"]],
  ["print", "Digital print", "surface", ["deadstock"]],
  [
    "edge-finishing",
    "Edge finishing",
    "construction",
    ["deadstock", "reclaimed"],
  ],
  ["applique", "Appliqué", "construction", ["deadstock", "reclaimed"]],
  ["patchwork", "Patchwork", "construction", ["deadstock", "reclaimed"]],
  ["quilting", "Quilting", "construction", ["deadstock", "reclaimed"]],
  [
    "visible-mending",
    "Visible mending",
    "construction",
    ["deadstock", "reclaimed"],
  ],
];

export const TECHNIQUES: readonly Technique[] = TECHNIQUE_ROWS.map(
  ([slug, name, kind, allowedStreams], index) => ({
    slug,
    name,
    kind,
    allowedStreams,
    order: index + 1,
  }),
);

export const PATTERNS: readonly Pattern[] = [
  { slug: "none", name: "No pattern", note: "Raw linen, hemmed", order: 1 },
  {
    slug: "tonal-logo",
    name: "Tonal logo",
    note: "Single corner mark",
    order: 2,
  },
  {
    slug: "placement",
    name: "Placement print",
    note: "Centred motif",
    order: 3,
  },
  {
    slug: "embroidery",
    name: "Embroidery motif",
    note: "Stitched monogram",
    order: 4,
  },
];

const LAYOUT_ROWS: readonly [string, string, Layout["kind"]][] = [
  ["grid", "Grid", "repeat"],
  ["half-drop", "Half drop", "repeat"],
  ["brick", "Brick", "repeat"],
  ["mirror", "Mirror", "repeat"],
  ["single", "Single", "repeat"],
  ["corner", "Corner", "placement"],
  ["center", "Centre", "placement"],
  ["border", "Border", "placement"],
];

export const LAYOUTS: readonly Layout[] = LAYOUT_ROWS.map(
  ([slug, name, kind], index) => ({
    slug,
    name,
    kind,
    order: index + 1,
  }),
);

export const PRODUCERS: readonly Producer[] = [
  {
    slug: "karachi-patchwork-studio",
    name: "Karachi Patchwork Studio",
    location: "Karachi, Pakistan",
    capabilities: ["patchwork", "denim", "totes", "small accessories"],
    supportedStreams: ["reclaimed"],
    minimumOrder: 10,
    leadTime: "7–10 days",
    reason:
      "Specialises in mixed reclaimed panels and turns shade variation into a design feature.",
    order: 1,
  },
  {
    slug: "lahore-home-textile-unit",
    name: "Lahore Home Textile Unit",
    location: "Lahore, Pakistan",
    capabilities: ["tablecloths", "aprons", "napkins", "embroidery"],
    supportedStreams: ["deadstock"],
    minimumOrder: 15,
    leadTime: "5–8 days",
    reason:
      "Deadstock linen and hospitality textiles are its core, with tonal embroidery in-house.",
    order: 2,
  },
  {
    slug: "delhi-embroidery-workshop",
    name: "Delhi Embroidery Workshop",
    location: "Delhi, India",
    capabilities: ["embroidery", "appliqué", "logo placement", "finishing"],
    supportedStreams: ["deadstock", "reclaimed"],
    minimumOrder: 10,
    leadTime: "6–9 days",
    reason:
      "A flexible alternative for embroidery, appliqué, placement, and finishing.",
    order: 3,
  },
];
